INSERT INTO `developers` VALUES (1,'nintendo');
INSERT INTO `developers` VALUES (2,'sony');
INSERT INTO `developers` VALUES (3,'computer');

INSERT INTO `systems` VALUES (1,1,'Nintendo Entertainment System','nes','c',0);
INSERT INTO `systems` VALUES (2,1,'Super Nintendo Entertainment System','snes','c',1);
INSERT INTO `systems` VALUES (3,1,'Nintendo 64','n64','c',2);
INSERT INTO `systems` VALUES (4,1,'Gameboy','gb','p',0);
INSERT INTO `systems` VALUES (5,1,'Gameboy Color','gbc','p',1);
INSERT INTO `systems` VALUES (6,1,'Gameboy Advance','gba','p',2);
INSERT INTO `systems` VALUES (7,2,'Playstation (One)','psx','c',0);
INSERT INTO `systems` VALUES (8,2,'Playstation 2','ps2','c',1);
INSERT INTO `systems` VALUES (9,2,'Playstation Portable','psp','p',0);
INSERT INTO `systems` VALUES (10,3,'DosBox','dos','',0);

INSERT INTO `games` VALUES (3,'q','Q-Bert','q-bert',49,'Q-Bert');
INSERT INTO `games` VALUES (4,'p','Pokemon Red and Blue','pokemon-red-and-blue',48,'Pokemon_red_and_blue');
INSERT INTO `games` VALUES (5,'b','Blast Corps','blast-corps',49,'Blast_Corps');
INSERT INTO `games` VALUES (6,'f','Final Fantasy','final-fantasy',54,'Final_Fantasy_(video_game)');
INSERT INTO `games` VALUES (7,'f','Final Fantasy IV','final-fantasy-iv',48,'Final_Fantasy_IV');
INSERT INTO `games` VALUES (8,'f','Final Fantasy VII','final-fantasy-vii',48,'Final_Fantasy_VII');
INSERT INTO `games` VALUES (9,'f','Flying Dragon','flying-dragon',48,'Flying_Dragon');

INSERT INTO `system_games` VALUES (1,3);
INSERT INTO `system_games` VALUES (1,6);
INSERT INTO `system_games` VALUES (1,70);
INSERT INTO `system_games` VALUES (1,72);
INSERT INTO `system_games` VALUES (1,75);
INSERT INTO `system_games` VALUES (1,83);
INSERT INTO `system_games` VALUES (1,91);
INSERT INTO `system_games` VALUES (1,96);
INSERT INTO `system_games` VALUES (1,99);
INSERT INTO `system_games` VALUES (1,110);
INSERT INTO `system_games` VALUES (1,120);
INSERT INTO `system_games` VALUES (1,121);
INSERT INTO `system_games` VALUES (1,128);
INSERT INTO `system_games` VALUES (2,7);
INSERT INTO `system_games` VALUES (2,81);
INSERT INTO `system_games` VALUES (2,104);
INSERT INTO `system_games` VALUES (2,111);
INSERT INTO `system_games` VALUES (2,114);
INSERT INTO `system_games` VALUES (2,116);
INSERT INTO `system_games` VALUES (2,125);
INSERT INTO `system_games` VALUES (2,128);
INSERT INTO `system_games` VALUES (3,5);
INSERT INTO `system_games` VALUES (3,9);
INSERT INTO `system_games` VALUES (3,76);
INSERT INTO `system_games` VALUES (3,78);
INSERT INTO `system_games` VALUES (3,85);
INSERT INTO `system_games` VALUES (3,86);
INSERT INTO `system_games` VALUES (3,94);
INSERT INTO `system_games` VALUES (3,102);
INSERT INTO `system_games` VALUES (3,109);
INSERT INTO `system_games` VALUES (3,115);
INSERT INTO `system_games` VALUES (3,117);
INSERT INTO `system_games` VALUES (3,123);
INSERT INTO `system_games` VALUES (3,127);
INSERT INTO `system_games` VALUES (4,4);
INSERT INTO `system_games` VALUES (4,71);
INSERT INTO `system_games` VALUES (4,73);
INSERT INTO `system_games` VALUES (4,83);
INSERT INTO `system_games` VALUES (4,86);
INSERT INTO `system_games` VALUES (4,91);
INSERT INTO `system_games` VALUES (4,93);
INSERT INTO `system_games` VALUES (4,106);
INSERT INTO `system_games` VALUES (4,107);
INSERT INTO `system_games` VALUES (4,112);
INSERT INTO `system_games` VALUES (4,114);
INSERT INTO `system_games` VALUES (4,124);
INSERT INTO `system_games` VALUES (5,79);
INSERT INTO `system_games` VALUES (5,95);
INSERT INTO `system_games` VALUES (5,101);
INSERT INTO `system_games` VALUES (5,104);
INSERT INTO `system_games` VALUES (5,113);
INSERT INTO `system_games` VALUES (6,6);
INSERT INTO `system_games` VALUES (6,74);
INSERT INTO `system_games` VALUES (6,77);
INSERT INTO `system_games` VALUES (6,90);
INSERT INTO `system_games` VALUES (6,97);
INSERT INTO `system_games` VALUES (6,103);
INSERT INTO `system_games` VALUES (6,105);
INSERT INTO `system_games` VALUES (6,111);
INSERT INTO `system_games` VALUES (6,118);
INSERT INTO `system_games` VALUES (6,122);
INSERT INTO `system_games` VALUES (6,126);
INSERT INTO `system_games` VALUES (7,6);
INSERT INTO `system_games` VALUES (7,8);
INSERT INTO `system_games` VALUES (7,82);
INSERT INTO `system_games` VALUES (7,84);
INSERT INTO `system_games` VALUES (7,86);
INSERT INTO `system_games` VALUES (7,92);
INSERT INTO `system_games` VALUES (7,104);
INSERT INTO `system_games` VALUES (7,105);
INSERT INTO `system_games` VALUES (7,125);
INSERT INTO `system_games` VALUES (7,128);
INSERT INTO `system_games` VALUES (8,89);
INSERT INTO `system_games` VALUES (8,128);
INSERT INTO `system_games` VALUES (9,6);
INSERT INTO `system_games` VALUES (9,82);
INSERT INTO `system_games` VALUES (9,88);
INSERT INTO `system_games` VALUES (9,100);
INSERT INTO `system_games` VALUES (9,111);
INSERT INTO `system_games` VALUES (9,119);
INSERT INTO `system_games` VALUES (9,124);
INSERT INTO `system_games` VALUES (9,129);
INSERT INTO `system_games` VALUES (10,80);
INSERT INTO `system_games` VALUES (10,87);
INSERT INTO `system_games` VALUES (10,98);
INSERT INTO `system_games` VALUES (10,108);
INSERT INTO `system_games` VALUES (10,118);

INSERT INTO `tags` VALUES (1,'completionist',1,1);
INSERT INTO `tags` VALUES (2,'collecting',1,1);
INSERT INTO `tags` VALUES (3,'grinding',1,1);
INSERT INTO `tags` VALUES (4,'unlocking',1,1);
INSERT INTO `tags` VALUES (5,'exploration',1,1);
INSERT INTO `tags` VALUES (6,'death',1,1);
INSERT INTO `tags` VALUES (7,'quick',1,1);
INSERT INTO `tags` VALUES (8,'time consuming',1,1);
INSERT INTO `tags` VALUES (9,'kills',1,1);
INSERT INTO `tags` VALUES (10,'time trial',1,1);
INSERT INTO `tags` VALUES (11,'multiplayer',1,1);
INSERT INTO `tags` VALUES (12,'points',1,1);
INSERT INTO `tags` VALUES (13,'fail',1,1);
INSERT INTO `tags` VALUES (14,'survial',1,1);
INSERT INTO `tags` VALUES (15,'minimalist',1,1);